### ISSUE TITLE
Add types for typescript

### ISSUE THREAD

**Issue by ExeAy** [KittyGiraudel/react-a11y-footnotes#85]
This component is missing types, which is making typescript apps complain. I was thinking about adding them to [the DefinitelyTyped repo](https://github.com/DefinitelyTyped/DefinitelyTyped) but maybe you want the types to be here?

**Comment by KittyGiraudel** [comment]
Hello.

I know nothing about TypeScript, but if you want to submit a PR, I’m happy accepting it and releasing a new version. :)

**Comment by ExeAy** [comment]
Sure thing, I'll get back to you with a PR later.

**Comment by KittyGiraudel** [comment]
Released in 0.5.0. Thank you!

**Comment by ExeAy** [comment]
No probelm. And thank you for a fast publish! Found a bug though, seems like the type definitions weren't included in the release. I opened a new PR that should fix it.

**Comment by KittyGiraudel** [comment]
Fixed again! Thank you. 😅
